// Generated by CoffeeScript 1.8.0
(function() {
  var Path, Q;

  Path = require('path');

  Q = require('q');

  module.exports = {
    preBuild: function(app) {
      return function(context) {
        var content, p, path, relative;
        relative = function(p) {
          return Path.relative(context.path, p);
        };
        path = Path.resolve(__dirname, 'plugins.js');
        content = "module.exports={";
        content += ((function() {
          var _i, _len, _ref, _results;
          _ref = app.pluginFolders;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            p = _ref[_i];
            _results.push("require('" + (relative(p)) + "')");
          }
          return _results;
        })()).join(',');
        content += "};";
        console.log('writing ', content, 'to', path);
        return context.write(path, content).then((function(_this) {
          return function() {
            return Q.all((function() {
              var _i, _len, _ref, _results;
              _ref = app.plugins;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                p = _ref[_i];
                _results.push(typeof p.preBuild === "function" ? p.preBuild(context) : void 0);
              }
              return _results;
            })());
          };
        })(this));
      };
    }
  };

}).call(this);
