// Generated by CoffeeScript 1.8.0
var Character, Context, Line, Setting;

Context = require('mitudomoe').Context;

Character = require('mitudomoe-character');

Setting = require('mitudomoe-setting');

Line = require('mitudomoe-line');

module.exports = function(app) {
  app.use(Character);
  app.use(Setting);
  app.use(Line);
  return app.globalStorage = {};
};
